opacity-rule = [
    "85:class_g = 'Alacritty'",
    "85:class_g = 'Code'",
    "85:class_g = 'Thunar'",
    "85:class_g = 'dmenu'",
    "85:class_g = 'Simplenote'",
    "85:class_g = 'Brave-browser'",
    "85:class_g = 'firefox'",
    "85:class_g = 'Sxiv'",

];

blur: 
{
    method = "dual_kawase";
    strength = 2;
}

backend = "glx";
